export enum Capabilities {
  Actuator = "Actuator",
  Battery = "Battery",
  ChangeLevel = "ChangeLevel",
  ColorTemperature = "ColorTemperature",
  Configuration = "Configuration",
  DoubleTapableButton = "DoubleTapableButton",
  HoldableButton = "HoldableButton",
  Initialize = "Initialize",
  Light = "Light",
  Notification = "Notification",
  Outlet = "Outlet",
  PowerMeter = "PowerMeter",
  PresenceSensor = "PresenceSensor",
  PushableButton = "PushableButton",
  Refresh = "Refresh",
  Sensor = "Sensor",
  Switch = "Switch",
  SwitchLevel = "SwitchLevel",
  Telnet = "Telnet",
  TemperatureMeasurement = "TemperatureMeasurement",
  WaterSensor = "WaterSensor",
}
